### ISSUE TITLE
wrongful orphans?

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#17] opened 2020-12-04 00:25 UTC
I see that some files are in orphans whenever they are more likely were
part of the recent study collection (on Dec 1st):

    [bids@rolando VIDS] > ls 2020/
    10  11

    [bids@rolando VIDS] > ls orphans/ | tail
    2020.11.30.12.38.51_2020.11.30.13.01.02.mkv
    2020.11.30.13.01.05_2020.11.30.19.19.32.mkv
    2020.12.01.13.46.46_2020.12.01.13.46.52.mkv
    2020.12.01.13.46.54_2020.12.01.13.48.50.mkv
    2020.12.01.13.48.52_2020.12.01.13.49.09.mkv
    2020.12.01.13.49.36_2020.12.01.13.50.14.mkv
    2020.12.01.13.50.16_2020.12.01.13.55.25.mkv
    2020.12.01.13.56.10_2020.12.01.13.59.03.mkv
    2020.12.01.13.59.06_2020.12.01.16.58.47.mkv
    otherFakeVideo.mkv

    [bids@rolando VIDS] > ls /inbox/DICOM/2020/12/01
    A003438

so I guess some matching needs to be fixed up?

**Comment by andycon** [comment] 2020-12-04 04:32
Thanks. This was caused by an error in comparing times. 
the following syntax with, e.g., g=45, h=100, returned true:
[[ $g > $h ]]

not sure why. testing this on command line bash seemed to work... but inside the script these variables must have been marked as strings...

changing syntax to [ $(( "$g" )) -gt $(( $h )) ]

fixed the bug.

**Closed** 2021-01-08 21:04 UTC
